MCU = RP2040				# MCU name
BOOTLOADER = rp2040			# bootloader selection
LTO_ENABLE = yes			# link time optimization -- achieves a smaller compiled size
RGB_MATRIX_ENABLE = no		# rgb support
IDLE_TIMEOUT_ENABLE = yes
VIA_ENABLE = yes			# via support
TAP_DANCE_ENABLE = no		# tab dance
LEADER_ENABLE = yes			# leader key support
UNICODE_ENABLE = yes		# unicode support
#UNICODEMAP_ENABLE = yes
